# fly.toml app configuration file generated for backend-green-thunder-5490 on 2025-10-05T03:44:34-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-green-thunder-5490'
primary_region = "iad"

[build]
dockerfile = "Dockerfile"

[env]
ENVIRONMENT = "production"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 8_000
min_machines_running = 0
processes = [ "app" ]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "2gb"